# Global ServerName to suppress warnings
ServerName localhost

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot "/var/www/html/backend/public"

    Alias /TAIPO "/var/www/html/frontend/dist"
    <Directory "/var/www/html/frontend/dist">
        AllowOverride All
        Require all granted
    </Directory>

    <Location "/TAIPO/api">
        ProxyPass "fcgi://127.0.0.1:9000/var/www/html/backend/public/index.php"
    </Location>

    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/html/backend/public/$1
</VirtualHost>
